#define PACKAGE_NAME "l1_logreg"
#define PACKAGE_TARNAME "l1_logreg"
#define PACKAGE_VERSION "0.8.2"
#define PACKAGE_STRING "l1_logreg 0.8.2"
#define PACKAGE_BUGREPORT "deneb1@stanford.edu"
#define PACKAGE "l1_logreg"
#define VERSION "0.8.2"
